source "https://rubygems.org"

# Specify your gem's dependencies in karimado.gemspec.
gemspec

# lint
gem "rubocop"
gem "standard"

# test
gem "rspec"
gem "rspec-rails"
gem "shoulda-matchers"
gem "factory_bot_rails"
gem "database_cleaner-active_record"
gem "timecop"

# doc
gem "yard"
gem "redcarpet"

# lsp
gem "solargraph"

# web development
gem "puma"
gem "sqlite3"
